
server:
    context-path: /samples
    port: 8080
spring:
    profiles:
        active: local
# ssf 相关配置
ssf:
    swagger:
        basePackage: com.samples
    datasource:
        master:
            url: jdbc:mysql://localhost:3306/test?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
            username: root
            password:
    include-stacktrace: always

mybatis:
    type-aliases-package: com.samples.pojo
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers: com.samples.dao.ISamplesMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  path: /tmp
